### ISSUE TITLE
Kerguelen Plateau bathy update

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/blueant#25]
there's this, https://data.gov.au/dataset/ds-ga-a05f7893-007f-7506-e044-00144fdd4fa6/details?q=

seems to have the same extent and resolution as `raadtools::topofile("kerguelen")`, but updated

the AGIS grid link is on this page: https://data.gov.au/dataset/ds-ga-a05f7893-007f-7506-e044-00144fdd4fa6/distribution/dist-ga-a05f7893-007f-7506-e044-00144fdd4fa6-0/?q=

**Comment by raymondben** [comment]
Added, https://github.com/AustralianAntarcticDivision/blueant/commit/a73dfa8b8ddd4c5461884cc39dcf6a9f156640ce
Files end up in the `d28rz98at9flks.cloudfront.net/71552/` folder.
