### ISSUE TITLE
AMSR2 3152 v5 can be discarded

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/blueant#31]
we can save a bit of space with a reject_download here  (about 14Gb on disk)

```
x<- blueant::sources("Artist AMSR2 near-real-time 3.125km sea ice concentration")

x$method[[1]]$reject_download <- ".*v5.(tif|hdf)"  ## avoid the v5 files (v5.4 is current)
```

https://seaice.uni-bremen.de/sea-ice-concentration/amsre-amsr2/information/

**Comment by mdsumner** [comment]
although ... it seems there's only v5 on our disk for the period 2018-10-28 - 2018-11-21, so I'll keep having look

**Comment by raymondben** [comment]
our local config only syncs the current year for this data set, to reduce run time. I'll run it manually for 2018 (assuming 5.4 files do actually exist for 2018?)

**Comment by mdsumner** [comment]
ah, no - they don't exist - I've emailed them - we have all the files don't bother running

(I think I was accidentally getting all the right files in my listing, but now it's a bit more deliberate :)

**Comment by mdsumner** [comment]
I contacted again (there was a .tiff in the mix) and I think they will clean up all the overlap.
