### ISSUE TITLE
gridded argo data

### ISSUE THREAD

**Issue by lavyrajah** [AustralianAntarcticDivision/blueant#32]
can we please get these data in the collection? 

 https://sio-argo.ucsd.edu/RG_Climatology.html 

files look like RG_ArgoClim_Temp.nc. RG_ArgoClim_Salinity_2019.nc RG_ArgoClim_202201_2019.nc 

can provide more details :) just here with Mike S discussing ;)

**Comment by raymondben** [comment]
Done https://github.com/AustralianAntarcticDivision/blueant/commit/7e70366f53a01534d17a67a0a8aaf15d5b8030ff

**Comment by raymondben** [comment]
(See files in `sio-argo.ucsd.edu/pub/www-argo/RG/`)
