### ISSUE TITLE
Authorisation failure on GHRSST MUR SST after blueant update

### ISSUE THREAD

**Issue by cmundy** [AustralianAntarcticDivision/blueant#34]
I have been using the blueant package to keep my "GHRSST Level 4 MUR Global Foundation SST v4.1" ncdf file archive update. This has been working nicely for the past few years, but this recent update (in the last week or so) has triggered an authorisation issue.

I can login to Earthdata with user/pass just fine and access the files through the browser, so not an access related issue. 

![image](https://github.com/AustralianAntarcticDivision/blueant/assets/10701195/8b57ff8e-a893-43ff-a755-3244e11f3875)

Hope you can help

Cheers (and thanks)

Craig

**Comment by cmundy** [comment]
Hi Ben,

Thanks for getting back in touch so quickly.

Using your code …



Fri Mar  8 09:10:33 2024
Synchronizing dataset: GHRSST Level 4 MUR Global Foundation SST v4.1
Source URL https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03/01
--------------------------------------------------------------------------------------------

this dataset path is: C:\Users\cmundy\AppData\Local\Temp\Rtmp0aRISk/cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03/01 ...
Downloading: 1.4 kB
 1 download links, 2 links to visit done.
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03 ...
Downloading: 1.3 kB
 0 download links, 6 links to visit done.
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024 ...
Downloading: 1.3 kB
 done.
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03/02 ...
Downloading: 1.4 kB
 done.
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03/03 ...
Downloading: 1.4 kB
 done.
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03/04 ...
Downloading: 1.4 kB
 done.
visiting https://cmr.earthdata.nasa.gov/virtual-directory/collections/C1996881146-POCLOUD/temporal/2024/03/05 ...
Downloading: 1.4 kB
 done.
downloading file 1 of 5: https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240302090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc ...
Downloading: 27 B      downloading file 2 of 5: https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240303090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc ...
Downloading: 27 B      downloading file 3 of 5: https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240304090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc ...
Downloading: 27 B      downloading file 4 of 5: https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240305090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc ...
Downloading: 27 B      downloading file 5 of 5: https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240306090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc ...
Downloading: 27 B
Fri Mar  8 09:10:53 2024 dataset synchronization complete: GHRSST Level 4 MUR Global Foundation SST v4.1
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  Error downloading https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240302090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc: Client error: (401) Unauthorized
2: In doTryCatch(return(expr), name, parentenv, handler) :
  Error downloading https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240303090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc: Client error: (401) Unauthorized
3: In doTryCatch(return(expr), name, parentenv, handler) :
  Error downloading https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240304090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc: Client error: (401) Unauthorized
4: In doTryCatch(return(expr), name, parentenv, handler) :
  Error downloading https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240305090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc: Client error: (401) Unauthorized
5: In doTryCatch(return(expr), name, parentenv, handler) :
  Error downloading https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20240306090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc: Client error: (401) Unauthorized

Sessioninfo

> sessionInfo()
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8    LC_MONETARY=English_Australia.utf8
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.utf8

time zone: Australia/Hobart
tzcode source: internal

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] blueant_0.11.0    bowerbird_0.14.2  tictoc_1.2        R.utils_2.12.3    R.oo_1.26.0       R.methodsS3_1.8.2
[7] lubridate_1.9.3   forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4       purrr_1.0.2       readr_2.1.5
[13] tidyr_1.3.1       tibble_3.2.1      ggplot2_3.5.0     tidyverse_2.0.0   fs_1.6.3          sf_1.0-15

loaded via a namespace (and not attached):
[1] tidyselect_1.2.0   fastmap_1.1.1      promises_1.2.1     digest_0.6.34      timechange_0.3.0
 [6] mime_0.12          lifecycle_1.0.4    ellipsis_0.3.2     processx_3.8.3     terra_1.7-71
[11] magrittr_2.0.3     compiler_4.3.3     rlang_1.1.3        utf8_1.2.4         knitr_1.45
[16] askpass_1.2.0      htmlwidgets_1.6.4  pkgbuild_1.4.3     classInt_0.4-10    curl_5.2.1
[21] xml2_1.3.6         plyr_1.8.9         websocket_1.4.1    pkgload_1.3.4      KernSmooth_2.23-22
[26] miniUI_0.1.1.1     withr_3.0.0        sys_3.4.2          grid_4.3.3         fansi_1.0.6
[31] urlchecker_1.0.1   profvis_0.3.8      xtable_1.8-4       e1071_1.7-14       colorspace_2.1-0
[36] future_1.33.1      globals_0.16.2     scales_1.3.0       cli_3.6.2          rmarkdown_2.26
[41] generics_0.1.3     remotes_2.4.2.1    rstudioapi_0.15.0  httr_1.4.7         tzdb_0.4.0
[46] sessioninfo_1.2.2  readxl_1.4.3       chromote_0.2.0     DBI_1.2.2          cachem_1.0.8
[51] proxy_0.4-27       rvest_1.0.4        assertthat_0.2.1   parallel_4.3.3     selectr_0.4-2
[56] cellranger_1.1.0   vctrs_0.6.5        devtools_2.4.5     jsonlite_1.8.8     hms_1.1.3
[61] listenv_0.9.1      units_0.8-5        glue_1.7.0         parallelly_1.37.1  ps_1.7.6
[66] codetools_0.2-19   stringi_1.8.3      gtable_0.3.4       later_1.3.2        munsell_0.5.0
[71] pillar_1.9.0       htmltools_0.5.7    openssl_2.1.1      R6_2.5.1           shiny_1.8.0
[76] evaluate_0.23      memoise_2.0.1      httpuv_1.6.14      class_7.3-22       Rcpp_1.0.12
[81] xfun_0.42          usethis_2.2.3      pkgconfig_2.0.3
>

**Comment by cmundy** [comment]
Hi Ben,

Thought I would check … I can still access the netcdf files manually through the browser .. so that shouldn’t be a problem.

***@***.***

**Comment by raymondben** [comment]
Thanks Craig. I get the same error now and was able to track it down to a recent change in v5.2.1 of the curl package (see https://github.com/jeroen/curl/issues/260).
I've updated bowerbird and blueant: could you reinstall from GitHub please:
```
remotes::install_github("AustralianAntarcticDivision/blueant")
```
(bowerbird should automatically update as part of that.)

And let's see how that goes ...

**Comment by cmundy** [comment]
Brilliant!!

Thanks heaps Ben .. back up and running.

For context,  I am using bowerbird/blueant as part of an automated updated on Marine Heat Wave status for Tas to help out NRE. I updated the netcdfs on a schedule and then process the .ncs and run the MHW classification and produce reports with rMarkdown/Quarto.

Your packages made my life a lot easier to get the automation running!!

Craig

**Comment by raymondben** [comment]
Great! (And thanks for the context, always nice to know when things turn out to actually be useful outside of our own little world!)
